import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import { ModalProvider } from "@/providers/modal-provider";
import { TosterProvider } from "@/providers/toast-provider";
import "./globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "@/providers/theme-provider";
//import prismadb from "@/lib/prismadb";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Dashbored",
  description: "Generated by Deaa ALdin ALawad",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
        //{inter.className}
        //className="max-w-7xl mx-auto h-full "
        >
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <TosterProvider />
            <ModalProvider />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
